$injector.inject('window', ()=>window)
$injector.inject('global', ()=>window)
$injector.inject('prompt', ()=>prompt)
$injector.inject('document', ()=>document)
$injector.inject('store', ()=>store)
$injector.inject('renderer', ()=>renderer)
