export const LOAD_STATE = 'LOAD_STATE'
export const SELECT_LIST = 'SELECT_LIST'
export const ADD_LIST = 'ADD_LIST'
export const REMOVE_LIST = 'REMOVE_LIST'
export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const TOGGLE_DONE_ITEM = 'TOGGLE_DONE_ITEM'
