$injector.define('prompt', ()=>window.prompt)
$injector.define('window', ()=>window)
$injector.define('global', ()=>window)
$injector.define('document', ()=>window.document)
$injector.define('Observer', ()=>window.Observer)
