$injector.inject('prompt', ()=>window.prompt)
$injector.inject('window', ()=>window)
$injector.inject('global', ()=>window)
$injector.inject('document', ()=>window.document)
$injector.inject('Observer', ()=>window.Observer)
$injector.inject('renderer', ()=>window.renderer)
